### ISSUE TITLE
invalid attribute for formula 'r-hub/cran/autobrew': version (nil)

### ISSUE THREAD

**Issue by yihui** [r-hub/homebrew-cran#8]
```sh
$ brew tap r-hub/cran
==> Tapping r-hub/cran
Cloning into '/usr/local/Homebrew/Library/Taps/r-hub/homebrew-cran'...
Error: Invalid formula: /usr/local/Homebrew/Library/Taps/r-hub/homebrew-cran/Formula/autobrew.rb
Error: Cannot tap r-hub/cran: invalid syntax in tap!
invalid attribute for formula 'r-hub/cran/autobrew': version (nil)
The command "brew tap r-hub/cran" failed and exited with 1 during .

$ brew --version
Homebrew 2.2.10-12-gb6812d2
Homebrew/homebrew-core (git revision 2575b; last commit 2020-03-11)
Homebrew/homebrew-cask (git revision d625d3; last commit 2020-03-11)
```

This might be related to a recent change https://github.com/Homebrew/brew/pull/7109. I'm not a Homebrew expert, and don't know how to fix it (sounds like you need to add a version to the formula, or tag the repo).

**Comment by jeroen** [comment]
Thanks! I've added a version attribute.

By the way I am now mostly working of [my own homebrew fork](https://github.com/autobrew/homebrew-core) because upstream homebrew no longer supports macos 10.11 (which is what CRAN uses). And also their formulae were changing/breaking too frequently for me to keep up with.

I hope to merge that repository back with this one at some point.

**Comment by yihui** [comment]
Thank you!
